import React from 'react';
import gooseCox from '../../resources/gooseCox.png';
import tunaBingo from '../../resources/tunaBingo.png';
import everythingBingo from '../../resources/everythingBingo.png';
import redacted from '../../resources/redacted.png';

import './PreviousEvents.css';

const PreviousEvents = () => {
    return (
        <div className="PreviousEvents">
            <div className="previousEvent">
                <h2 className="previousEventH2">In October of 2023 Goose's Gringos defeated MX and the Arcanes in a bloody war that saw both teams competing to see who could get all 12 purples from CoX first.</h2>
                <img src={gooseCox} alt="Goose CoX Bingo 2023" className="event-image" />
                <h3 className="previousEventH3">Goose CoX Bingo 2023</h3>
            </div>
            <div className="previousEvent">
                <h2 className="previousEventH2">In Feburary of 2024 Team Nsync defeated Team TunaPhish in a brutal race to see who can complete all three raids first.</h2>
                <img src={tunaBingo} alt="Tuna Bingo 2024" className="event-image" />
                <h3 className="previousEventH3">Tuna Bingo 2024</h3>
            </div>
            <div className="previousEvent">
                <h2 className="previousEventH2">In August of 2024 Team Terry's Cabin Boys defeated Team J_mes Legends in a perilous event that spanned all of Gielinor</h2>
                <img src={everythingBingo} alt="Everything Bingo 2024" className="event-image" />
                <h3 className="previousEventH3">Everything Bingo 2024</h3>
            </div>
            <div className="previousEvent">
                <h2 className="previousEventH2">What upcoming event could this be?</h2>
                <img src={redacted} alt="REDACTED" className="event-image" />
                <h3 className="previousEventH3">REDACTED Bingo REDACTED</h3>
            </div>
            <h5>All Images are generated by AI, not actual art. (Except for the cat, he's real).</h5>
        </div>
    );
}

export default PreviousEvents;