export const templeMap = ([
	["Attack",1],
	["Defence",2],
	["Strength",3],
	["Hitpoints",4],
	["Ranged",5],
	["Prayer",6],
	["Magic",7],
	["Cooking",8],
	["Woodcutting",9],
	["Fletching",10],
	["Fishing",11],
	["Firemaking",12],
	["Crafting",13],
	["Smithing",14],
	["Mining",15],
	["Herblore",16],
	["Agility",17],
	["Thieving",18],
	["Slayer",19],
	["Farming",20],
	["Runecraft","Runecrafting",21],
	["Hunter",22],
	["Construction",23],
	["Beginner_Clue","Beginner Clues",26],
	["Easy_Clue","Easy Clues",27],
	["Medium_Clue","Medium Clues",28],
	["Hard_Clue","Hard Clues",29],
	["Elite_Clue","Elite Clues",30],
	["Master_Clue","Master Clues",31],
	["Abyssal_Sire","Sire",33],
	["Alchemical_Hydra","Hydra",34],
	["Barrows_Chests", "Barrows",35],
	["Bryophyta",36],
	["Callisto",37],
	["Cerberus",38],
	["Chambers_of_Xeric","CoX",39],
	["Chambers_of_Xeric_Challenge_Mode","CM",40],
	["Chaos_Elemental","Chaos Elemental",41],
	["Chaos_Fanatic","Chaos Fanatic",42],
	["Commander_Zilyana","Zily",43],
	["Corporeal_Beast","Corp",44],
	["Crazy_Archaeologist","Crazy Arch",45],
	["Dagannoth_Prime","Prime",46],
	["Dagannoth_Rex","Rex",47],
	["Dagannoth_Supreme","Supreme",48],
	["Deranged_Archaeologist","Degranged Arch",49],
	["General_Graardor","Graardor",50],
	["Giant_Mole","Giant Mole",51],
	["Grotesque_Guardians","Grotesque Guardians",52],
	["Hespori",53],
	["Kalphite_Queen","KQ",54],
	["King_Black_Dragon","KBD",55],
	["Kraken",56],
	["KreeArra","Kree",57],
	["Kril_Tsutsaroth","Kril",58],
	["Mimic",59],
	["Obor",60],
	["Sarachnis",61],
	["Scorpia",62],
	["Skotizo",63],
	["The_Gauntlet","Gauntlet",64],
	["The_Corrupted_Gauntlet","CG",65],
	["Theatre_of_Blood","ToB",66],
	["Thermonuclear_Smoke_Devil","Thermy",67],
	["TzKal-Zuk",68],
	["TzTok-Jad",69],
	["Venenatis",70],
	["Vetion",71],
	["Vorkath",72],
	["Wintertodt",73],
	["Zalcano",74],
	["Zulrah",75],
	["The_Nightmare","Nightmare",82],
	["Tempoross",84],
	["Theatre_of_Blood_Challenge_Mode","HMT ToB",85],
	["Phosani's_Nightmare","PNM",88],
	["Nex",89],
	["Rift",90],
	["Tombs_of_Amascut","ToA",93],
	["Tombs_of_Amascut_Expert","Expert ToA",94],
	["Phantom_Muspah",95],
	["Artio",96],
	["Calvarion",97],
	["Spindel",98],
	["Duke_Sucellus","Duke",100],
	["The_Leviathan","Leviathan",101],
	["The_Whisperer", "Whisperer",102],
	["Vardorvis",103],
	["Scurrius",104],
	["Lunar_Chests","Moons Of Peril",106],
	["Sol_Heredit","Colosseum",107],
]);