/* 
 * Structure:
 * [Temple Lookup Name, Display Name, Points, Temple Index, EHB/EHP]
*/

export const templeMap = [
    ["Overall", "Overall", 1, 0,0,"Skills/Overall.png"],
    ["Attack", "Attack", 1, 1,150000,"Skills/Attack.png"],
    ["Defence", "Defence", 1, 2,150000,"Skills/Defence.png"],
    ["Strength", "Strength", 1, 3,150000,"Skills/Strength.png"],
    ["Hitpoints", "Hitpoints", 1, 4,75000,"Skills/Hitpoints.png"],
    ["Ranged", "Ranged", 1, 5,150000,"Skills/Ranged.png"],
    ["Prayer", "Prayer", 1, 6,1000000,"Skills/Prayer.png"],
    ["Magic", "Magic", 1, 7,150000,"Skills/Magic.png"],
    ["Cooking", "Cooking", 1, 8,300000,"Skills/Cooking.png"],
    ["Woodcutting", "Woodcutting", 1, 9,100000,"Skills/Woodcutting.png"],
    ["Fletching", "Fletching", 1, 10,100000,"Skills/Fletching.png"],
    ["Fishing", "Fishing", 1, 11,80000,"Skills/Fishing.png"],
    ["Firemaking", "Firemaking", 1, 12,300000,"Skills/Firemaking.png"],
    ["Crafting", "Crafting", 1, 13,100000,"Skills/Crafting.png"],
    ["Smithing", "Smithing", 1, 14,270000,"Skills/Smithing.png"],
    ["Mining", "Mining", 1, 15,100000,"Skills/Mining.png"],
    ["Herblore", "Herblore", 1, 16,250000,"Skills/Herblore.png"],
    ["Agility", "Agility", 1, 17,100000,"Skills/Agility.png"],
    ["Thieving", "Thieving", 1, 18,300000,"Skills/Thieving.png"],
    ["Slayer", "Slayer", 1, 19,80000,"Skills/Slayer.png"],
    ["Farming", "Farming", 1, 20,450000,"Skills/Farming.png"],
    ["Runecraft", "Runecrafting", 1, 21,100000,"Skills/Runecraft.png"],
    ["Hunter", "Hunter", 1, 22,200000,"Skills/Hunter.png"],
    ["Construction", "Construction", 1, 23,300000,"Skills/Construction.png"],
    ["Easy Clue", "Easy Clues", 1, 27,15,"Items/Easy Clue.png"],
    ["Medium Clue", "Medium Clues", 1, 28,12,"Items/Medium Clue.png"],
    ["Hard Clue", "Hard Clues", 2, 29,6,"Items/Hard Clue.png"],
    ["Elite Clue", "Elite Clues", 2, 30,1,"Items/Elite Clue.png"],
    ["Master Clue", "Master Clues", 2, 31,.5,"Items/Master Clue.png"],
    ["LMS", "LMS",1, 32, 1000,"Misc/LMS.png"],
    ["Barrows Chests", "Barrows", 1, 35, 22, "Bosses/Barrows Chests.png"],
    ["Bryophyta", "Bryophyta", 1, 36, 6, "Bosses/Bryophyta.png"],
    ["Callisto", "Callisto", 1, 37, 85, "Bosses/Callisto.png"],
    ["Cerberus", "Cerberus", 1, 38, 54, "Bosses/Cerberus.png"],
    ["Chambers of Xeric", "CoX", 3, 39, 2.9, "Bosses/Chambers of Xeric.png"],
    ["Chambers of Xeric Challenge Mode", "CM", 3, 40, 2.4, "Bosses/Chambers of Xeric Challenge Mode.png"],
    ["Chaos Elemental", "Chaos Elemental", 1, 41, 48, "Bosses/Chaos Elemental.png"],
    ["Chaos Fanatic", "Chaos Fanatic", 1, 42, 80, "Bosses/Chaos Fanatic.png"],
    ["Commander Zilyana", "Zily", 2, 43, 30, "Bosses/Commander Zilyana.png"],
    ["Corporeal Beast", "Corp", 3, 44, 8.5, "Bosses/Corporeal Beast.png"],
    ["Crazy Archaeologist", "Crazy Arch", 1, 45, 75, "Bosses/Crazy Archaeologist.png"],
    ["Combined_DKS", "Combined DKS", 1, 201, 100, "Bosses/Combined_DKS.png"],
    ["Deranged Archaeologist", "Degranged Arch", 1, 49, 80, "Bosses/Deranged Archaeologist.png"],
    ["General Graardor", "Graardor", 2, 50, 31, "Bosses/General Graardor.png"],
    ["Giant Mole", "Giant Mole", 1, 51, 97, "Bosses/Giant Mole.png"],
    ["Grotesque Guardians", "Grotesque Guardians", 1, 52, 34, "Bosses/Grotesque Guardians.png"],
    ["Hespori", "Hespori", 1, 53, 50, "Bosses/Hespori.png"],
    ["Kalphite Queen", "KQ", 2, 54, 37, "Bosses/Kalphite Queen.png"],
    ["King Black Dragon", "KBD", 2, 55, 75, "Bosses/King Black Dragon.png"],
    ["Kraken", "Kraken", 1, 56, 90, "Bosses/Kraken.png"],
    ["KreeArra", "Kree", 2, 57, 30, "Bosses/KreeArra.png"],
    ["Kril Tsutsaroth", "Kril", 2, 58, 28, "Bosses/Kril Tsutsaroth.png"],
    ["Mimic", "Mimic", 1, 59, 50, "Bosses/Mimic.png"],
    ["Obor", "Obor", 1, 60, 6, "Bosses/Obor.png"],
    ["Sarachnis", "Sarachnis", 1, 61, 67, "Bosses/Sarachnis.png"],
    ["Scorpia", "Scorpia", 1, 62, 80, "Bosses/Scorpia.png"],
    ["Skotizo", "Skotizo", 1, 63, 0.5, "Bosses/Skotizo.png"],
    ["The Gauntlet", "Gauntlet", 1, 64, 10, "Bosses/The Gauntlet.png"],
    ["The Corrupted Gauntlet", "CG", 2, 65, 7.2, "Bosses/The Corrupted Gauntlet.png"],
    ["Theatre of Blood", "ToB", 3, 66, 2.9, "Bosses/Theatre of Blood.png"],
    ["Thermonuclear Smoke Devil", "Thermy", 1, 67, 100, "Bosses/Thermonuclear Smoke Devil.png"],
    ["TzKal-Zuk", "TzKal-Zuk", 3, 68, 0.9, "Bosses/TzKal-Zuk.png"],
    ["TzTok-Jad", "TzTok-Jad", 2, 69, 2.2, "Bosses/TzTok-Jad.png"],
    ["Venenatis", "Venenatis", 1, 70, 33, "Bosses/Venenatis.png"],
    ["Vetion", "Vetion", 1, 71, 35, "Bosses/Vetion.png"],
    ["Vorkath", "Vorkath", 2, 72, 34, "Bosses/Vorkath.png"],
    ["Wintertodt", "Wintertodt", 1, 73, 12, "Bosses/Wintertodt.png"],
    ["Zalcano", "Zalcano", 1, 74, 20, "Bosses/Zalcano.png"],
    ["Zulrah", "Zulrah", 2, 75, 39, "Bosses/Zulrah.png"],
    ["The Nightmare", "Nightmare", 2, 82, 11, "Bosses/The Nightmare.png"],
    ["Soul Wars Zeal", "Soul Wars", 1, 83, 200, "Misc/Soul Wars Zeal.png"],
    ["Tempoross", "Tempoross", 1, 84, 10, "Bosses/Tempoross.png"],
    ["Theatre of Blood Hard Mode", "HMT ToB", 3, 85, 2.7, "Bosses/Theatre of Blood Challenge Mode.png"],
    ["Phosani's Nightmare", "PNM", 3, 88, 6.7, "Bosses/Phosanis Nightmare.png"],
    ["Nex", "Nex", 2, 89, 15, "Bosses/Nex.png"],
    ["Rift", "Rift", 1, 90,7, "Bosses/Rift.png"],
    ["Tombs of Amascut", "ToA", 2, 93,3, "Bosses/Tombs of Amascut.png"],
    ["Tombs of Amascut Expert", "Expert ToA", 3, 94,2.6, "Bosses/Tombs of Amascut Expert.png"],
    ["Phantom Muspah", "Phantom Muspah", 2, 95, 25, "Bosses/Phantom Muspah.png"],
    ["Artio", "Artio", 1, 96, 50, "Bosses/Artio.png"],
    ["Calvarion", "Calvarion", 1, 97, 45, "Bosses/Calvarion.png"],
    ["Spindel", "Spindel", 1, 98, 50, "Bosses/Spindel.png"],
    ["Duke Sucellus", "Duke", 2, 100, 30, "Bosses/Duke Sucellus.png"],
    ["The Leviathan", "Leviathan", 2, 101, 25, "Bosses/The Leviathan.png"],
    ["The Whisperer", "Whisperer", 2, 102, 21, "Bosses/The Whisperer.png"],
    ["Vardorvis", "Vardorvis", 2, 103, 33, "Bosses/Vardorvis.png"],
    ["Scurrius", "Scurrius", 1, 104, 60, "Bosses/Scurrius.png"],
    ["Lunar Chests", "Moons Of Peril", 2, 106, 18, "Bosses/Lunar Chests.png"],
    ["Sol Heredit", "Colosseum", 3, 107, 2.5, "Bosses/Sol Heredit.png"],
    ["Araxxor", "Araxxor", 1, 109, 30, "Bosses/Araxxor.png"],
    ["The Hueycoatl", "Hueycoatl", 1, 110, 50, "Bosses/The Hueycoatl.webp"],
    ["Amoxliatl", "Amoxliatl", 1, 111, 50, "Bosses/Amoxliatl.webp"],
    ["Collections", "Collections Logged", 3, 114, 1, "Misc/Collections.webp"],
    ["The Royal Titans", "The Royal Titans", 1, 115, 30, "Bosses/The Royal Titans.webp"],
    ["Yama", "Yama", 3, 117, 15, "Bosses/Yama.webp"],
];
