/* 
 * Structure:
 * [Temple Lookup Name, Display Name, Points, Temple Index]
*/

export const templeMap = [
    ["Attack", "Attack", 1, 1],
    ["Defence", "Defence", 1, 2],
    ["Strength", "Strength", 1, 3],
    ["Hitpoints", "Hitpoints", 1, 4],
    ["Ranged", "Ranged", 1, 5],
    ["Magic", "Magic", 1, 7],
    ["Woodcutting", "Woodcutting", 1, 9],
    ["Fishing", "Fishing", 1, 11],
    ["Firemaking", "Firemaking", 1, 12],
    ["Mining", "Mining", 1, 15],
    ["Agility", "Agility", 1, 17],
    ["Thieving", "Thieving", 1, 18],
    ["Slayer", "Slayer", 1, 19],
    ["Runecraft", "Runecrafting", 1, 21],
    ["Hunter", "Hunter", 1, 22],
    ["Beginner Clue", "Beginner Clues", 1, 26],
    ["Easy Clue", "Easy Clues", 1, 27],
    ["Medium Clue", "Medium Clues", 1, 28],
    ["Hard Clue", "Hard Clues", 2, 29],
    ["Elite Clue", "Elite Clues", 2, 30],
    ["Master Clue", "Master Clues", 2, 31],
    ["LMS", "LMS",1, 32],
    ["Abyssal Sire", "Sire", 2, 33],
    ["Alchemical Hydra", "Hydra", 1, 34],
    ["Barrows Chests", "Barrows", 1, 35],
    ["Bryophyta", "Bryophyta", 1, 36],
    ["Callisto", "Callisto", 1, 37],
    ["Cerberus", "Cerberus", 1, 38],
    ["Chambers of Xeric", "CoX", 3, 39],
    ["Chambers of Xeric Challenge Mode", "CM", 3, 40],
    ["Chaos Elemental", "Chaos Elemental", 1, 41],
    ["Chaos Fanatic", "Chaos Fanatic", 1, 42],
    ["Commander Zilyana", "Zily", 2, 43],
    ["Corporeal Beast", "Corp", 3, 44],
    ["Crazy Archaeologist", "Crazy Arch", 1, 45],
    // ["Dagannoth Prime", "Prime", 1, 46],
    // ["Dagannoth Rex", "Rex", 1, 47],
    // ["Dagannoth Supreme", "Supreme", 1, 48],
    ["Combined_DKS", "Combined DKS",1,201],
    ["Deranged Archaeologist", "Degranged Arch", 1, 49],
    ["General Graardor", "Graardor", 2, 50],
    ["Giant Mole", "Giant Mole", 1, 51],
    ["Grotesque Guardians", "Grotesque Guardians", 1, 52],
    ["Hespori", "Hespori", 1, 53],
    ["Kalphite Queen", "KQ", 2, 54],
    ["King Black Dragon", "KBD", 2, 55],
    ["Kraken", "Kraken", 1, 56],
    ["KreeArra", "Kree", 2, 57],
    ["Kril Tsutsaroth", "Kril", 2, 58],
    ["Mimic", "Mimic", 1, 59],
    ["Obor", "Obor", 1, 60],
    ["Sarachnis", "Sarachnis", 1, 61],
    ["Scorpia", "Scorpia", 1, 62],
    ["Skotizo", "Skotizo", 1, 63],
    ["The Gauntlet", "Gauntlet", 1, 64],
    ["The Corrupted Gauntlet", "CG", 2, 65],
    ["Theatre of Blood", "ToB", 3, 66],
    ["Thermonuclear Smoke Devil", "Thermy", 1, 67],
    ["TzKal-Zuk", "TzKal-Zuk", 3, 68],
    ["TzTok-Jad", "TzTok-Jad", 2, 69],
    ["Venenatis", "Venenatis", 1, 70],
    ["Vetion", "Vetion", 1, 71],
    ["Vorkath", "Vorkath", 2, 72],
    ["Wintertodt", "Wintertodt", 1, 73],
    ["Zalcano", "Zalcano", 1, 74],
    ["Zulrah", "Zulrah", 2, 75],
    ["The Nightmare", "Nightmare", 2, 82],
    ["Soul Wars Zeal", "Soul Wars",1,83],
    ["Tempoross", "Tempoross", 1, 84],
    ["Theatre of Blood Challenge Mode", "HMT ToB", 3, 85],
    ["Phosani's Nightmare", "PNM", 3, 88],
    ["Nex", "Nex", 2, 89],
    ["Rift", "Rift", 1, 90],
    ["Tombs of Amascut", "ToA", 2, 93],
    ["Tombs of Amascut Expert", "Expert ToA", 3, 94],
    ["Phantom Muspah", "Phantom Muspah", 2, 95],
    ["Artio", "Artio", 1, 96],
    ["Calvarion", "Calvarion", 1, 97],
    ["Spindel", "Spindel", 1, 98],
    ["Duke Sucellus", "Duke", 2, 100],
    ["The Leviathan", "Leviathan", 2, 101],
    ["The Whisperer", "Whisperer", 2, 102],
    ["Vardorvis", "Vardorvis", 2, 103],
    ["Scurrius", "Scurrius", 1, 104],
    ["Lunar Chests", "Moons Of Peril", 2, 106],
    ["Sol Heredit", "Colosseum", 3, 107],
];
